spring:
  application:
    name: communication-service

  datasource:
    url: jdbc:h2:mem:testdb
    username: comservice
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    function:
      definition: userEvents
    stream:
      bindings:
        userEvents-in-0:
          destination: user.events
          content-type: application/json
          group: communication-service
          binder: rabbit
      rabbit:
        bindings:
          userEvents-in-0:
            consumer:
              exchangeType: fanout

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    appname: communication-service


springdoc:
  swagger-ui:
    path: /api-ui

management:
  endpoint:
    health:
      show-details: always
