spring:
  application:
    name: user-management-service
  config:
    import: optional:configserver:http://localhost:8888/
  datasource:
    url: jdbc:h2:file:~/h2db/user-management-service;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret-key: 057e726768a1c9d8b0fefb4d957277d996c4332811a966950186a1502f08267b
    expiration-time: 86400000

server:
  port: 8025
