spring:
  application:
    name: user-management-service
  config:
    import: optional:configserver:http://localhost:8888/
  datasource:
    url: jdbc:h2:file:~/h2db/user-management-service;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

security:
  jwt:
    secret-key: 374c09f29d14bb7f295fae49b44827ac54dec177ef52aa990d8663704c61d0d5
    expiration-time: 86400000

server:
  port: 8025